#!/bin/bash

# Floating point bash calculator (bc wrapper)
# Copyright (C) 2012 Ahmet Ay, Jack Holland, Adriana Sperlea

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# $1 = input for the bc program

# this function prints out how to use this script and then exits
function usage () {
	echo "Usage: calc <input for the bc program>"
	exit 0
}

if [ $# -ne 1 ]; then
	usage
fi

# prints calculation with 8 digits of precision (to the right of the decimal place)
echo "scale=8; $1 " | bc -l

